spring: 
  profiles: 
    active: prod
    
  application: 
    name: customer-service
---
spring:
  profiles: dev
  
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:~/test1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
server:
  port: 1111
  
---
spring:
  profiles: prod
  
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:~/test1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
server:
  port: 1112